apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: pvmvp27aw-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/jsmid/rhtap-qe:94330c4fd8edfffdc666eb3f424909134273bb6a@sha256:7b65b60094ad2bab301963143221d95ba29448da127f9d31583afff260a4fcf2
        name: container-image  
